/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 846a56dbfa2195257acd4425297bf2a7)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		AI: Ai;
		GITHUB_REPO_URL: string;
		GITHUB_TOKEN: string;
		GOOGLE_GENERATIVE_AI_API_KEY: string;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_REPO_URL" | "GITHUB_TOKEN" | "GOOGLE_GENERATIVE_AI_API_KEY">> {}
}
