-- Migration: 0001_initial_schema
-- Creates the five core relational tables for Gatekeeper AI.
-- Primary keys are UUID v4 TEXT values generated by crypto.randomUUID().
-- Timestamps are stored as TEXT using DEFAULT CURRENT_TIMESTAMP (ISO 8601).
-- Foreign key declarations are present for documentation; D1 does not enforce them by default.

CREATE TABLE IF NOT EXISTS users (
  id         TEXT    NOT NULL PRIMARY KEY,
  github_id  TEXT    NOT NULL UNIQUE,
  email      TEXT,
  name       TEXT    NOT NULL,
  avatar_url TEXT,
  created_at TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS repositories (
  id             TEXT NOT NULL PRIMARY KEY,
  github_repo_id TEXT NOT NULL UNIQUE,
  owner          TEXT NOT NULL,
  name           TEXT NOT NULL,
  installation_id TEXT,
  sync_status    TEXT NOT NULL DEFAULT 'pending'
                 CHECK(sync_status IN ('pending', 'syncing', 'synced', 'failed')),
  last_synced_at TEXT
);

CREATE TABLE IF NOT EXISTS repository_labels (
  id            TEXT NOT NULL PRIMARY KEY,
  repository_id TEXT NOT NULL REFERENCES repositories(id),
  name          TEXT NOT NULL,
  description   TEXT,
  color         TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_sessions (
  id            TEXT NOT NULL PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES users(id),
  repository_id TEXT NOT NULL REFERENCES repositories(id),
  title         TEXT NOT NULL,
  created_at    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sync_events (
  id            TEXT NOT NULL PRIMARY KEY,
  repository_id TEXT NOT NULL REFERENCES repositories(id),
  event_type    TEXT NOT NULL,
  commit_sha    TEXT,
  status        TEXT NOT NULL,
  processed_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
